# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ulkge6l_69nn6SGY1iGrWlDnnOOzuxj9
"""

try:
    from google.colab import drive
    drive.mount('/content/drive')
    BASE_PATH = "/content/drive/MyDrive/evermind_models/"
except:
    BASE_PATH = "./"

# train_advanced.py

import pandas as pd
import numpy as np
import time
import joblib
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier, StackingClassifier, IsolationForest
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.utils import resample

from xgboost import XGBClassifier


data = pd.read_csv("/content/drive/MyDrive/evermind_models/advanced_extended_dataset.csv")

# =========================
# ENCODE
# =========================
le = LabelEncoder()
data["state"] = le.fit_transform(data["state"])
# Encode TARGET (VERY IMPORTANT)
target_encoder = LabelEncoder()
data["intervention"] = target_encoder.fit_transform(data["intervention"])

# =========================
# FEATURE ENGINEERING
# =========================
data["hr_bp_ratio"] = data["heart_rate"] / (data["blood_pressure"] + 1)
data["temp_flag"] = (data["temperature"] > 99).astype(int)
data["hr_squared"] = data["heart_rate"] ** 2
data["bp_temp_interaction"] = data["blood_pressure"] * data["temperature"]

# =========================
# DATA BALANCING
# =========================
df_majority = data[data.intervention == 0]
df_minority = data[data.intervention == 1]

if len(df_minority) == 0 or len(df_majority) == 0:
    print("⚠️ Dataset has only one class. Skipping balancing.")
else:
    df_minority_upsampled = resample(
        df_minority,
        replace=True,
        n_samples=len(df_majority),
        random_state=42
    )

    data = pd.concat([df_majority, df_minority_upsampled])

# =========================
# FEATURES & TARGET
# =========================
features = [
    "heart_rate", "blood_pressure", "temperature", "state",
    "hr_bp_ratio", "temp_flag", "hr_squared", "bp_temp_interaction"
]

X = data[features]
y = data["intervention"]

# =========================
# SPLIT
# =========================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# =========================
# SCALING (ONLY FOR LR)
# =========================
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# =========================
# MODELS
# =========================
models = {
    "RandomForest": RandomForestClassifier(
        n_estimators=200,
        max_depth=10,
        min_samples_split=5
    ),
    "DecisionTree": DecisionTreeClassifier(max_depth=10),
    "LogisticRegression": LogisticRegression(max_iter=500),
    "XGBoost": XGBClassifier(eval_metric="logloss")
}

results = {}

# =========================
# TRAIN MODELS
# =========================
for name, model in models.items():

    print(f"\nTraining {name}...")

    start = time.time()

    if name == "LogisticRegression":
        model.fit(X_train_scaled, y_train)
        preds = model.predict(X_test_scaled)
    else:
        model.fit(X_train, y_train)
        preds = model.predict(X_test)

    end = time.time()

    acc = accuracy_score(y_test, preds)
    train_time = end - start
    throughput = len(X_train) / train_time

    print(classification_report(y_test, preds))

    results[name] = {
        "accuracy": acc,
        "training_time": train_time,
        "throughput": throughput
    }

    joblib.dump(model, BASE_PATH + f"{name}.pkl")

# =========================
# STACKING MODEL
# =========================
print("\nTraining Stacking Model...")

stack = StackingClassifier(
    estimators=[
        ("rf", models["RandomForest"]),
        ("xgb", models["XGBoost"])
    ],
    final_estimator=LogisticRegression()
)

start = time.time()
stack.fit(X_train, y_train)
end = time.time()

preds = stack.predict(X_test)

acc = accuracy_score(y_test, preds)
train_time = end - start
throughput = len(X_train) / train_time

results["Stacking"] = {
    "accuracy": acc,
    "training_time": train_time,
    "throughput": throughput
}

joblib.dump(stack, BASE_PATH + "stack_model.pkl")

# =========================
# ANOMALY MODEL
# =========================
print("\nTraining Anomaly Model...")

iso = IsolationForest(contamination=0.05)

start = time.time()
iso.fit(X)
end = time.time()

results["AnomalyModel"] = {
    "training_time": end - start,
    "throughput": len(X) / (end - start)
}

joblib.dump(iso, BASE_PATH + "anomaly.pkl")

# =========================
# SAVE SCALER + ENCODER
# =========================
joblib.dump(scaler, BASE_PATH + "scaler.pkl")
joblib.dump(le, BASE_PATH + "label_encoder.pkl")
joblib.dump(target_encoder, BASE_PATH + "target_encoder.pkl")

# =========================
# PLOTS (EXCLUDING ANOMALY FOR ACCURACY)
# =========================
plot_models = [m for m in results if m != "AnomalyModel"]

names = plot_models

accuracy_vals = [results[m]["accuracy"] for m in names]
time_vals = [results[m]["training_time"] for m in names]
throughput_vals = [results[m]["throughput"] for m in names]

# Accuracy Graph
plt.figure()
plt.bar(names, accuracy_vals)
plt.title("Accuracy Comparison")
plt.xticks(rotation=30)
plt.tight_layout()
plt.savefig(BASE_PATH + "accuracy.png")

# Training Time Graph
plt.figure()
plt.bar(names, time_vals)
plt.title("Training Time Comparison")
plt.xticks(rotation=30)
plt.tight_layout()
plt.savefig(BASE_PATH + "training_time.png")

# Throughput Graph
plt.figure()
plt.bar(names, throughput_vals)
plt.title("Throughput Comparison")
plt.xticks(rotation=30)
plt.tight_layout()
plt.savefig(BASE_PATH + "throughput.png")

print("\n✅ Training Complete. Models & graphs saved to:", BASE_PATH)

